#!/bin/bash
#
# Start the energymon service.
#
### BEGIN INIT INFO
# Provides:          energymon
# Required-Start:    $local_fs $syslog statsd
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: energymon
# Description:       energymon
### END INIT INFO

name=energymon
dir=/opt/energymon
exe=$dir/energymon.sh
exe1="$exe gas"
pid1=/var/run/gas.pid
exe2="$exe power"
pid2=/var/run/power.pid
exe3="$exe heating"
pid3=/var/run/heating.pid

opt_args=""

debug=0

if [ $debug == 1 ]; then
    opt_args="debug"
fi

. /lib/lsb/init-functions

function do_start() {
    log_begin_msg "Starting $name service"
    start-stop-daemon --start --quiet --pidfile $pid1 --exec $exe1 $opt_args
    start-stop-daemon --start --quiet --pidfile $pid2 --exec $exe2 $opt_args
    start-stop-daemon --start --quiet --pidfile $pid3 --exec $exe3 $opt_args
    log_end_msg $?
}

function do_stop() {
    log_begin_msg "Stopping $name service"
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pid1
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pid2
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pid3
    log_end_msg $?
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        do_start
        ;;
    *)
        echo "$0 {start|stop|restart}"
        ;;
esac
