#!/bin/bash
#
# Start the statsd service.
#
### BEGIN INIT INFO
# Provides:          statsd
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: statsd
# Description:       statsd
### END INIT INFO

dir=/opt/energymon
name=statsd
exe1=$dir/statsd.sh
pid1=/var/run/statsd.pid

. /lib/lsb/init-functions

function do_start() {
    log_begin_msg "Starting $name service"
    start-stop-daemon --start --quiet --pidfile $pid1 --exec $exe1
    log_end_msg $?
}

function do_stop() {
    log_begin_msg "Stopping $name service"
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pid1
    log_end_msg $?
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        do_start
        ;;
    *)
        echo "$0 {start|stop|restart}"
        ;;
esac
